
#General settings
[general]
	#Enable Tea
	tea = false
	#Enable Confetti
	confetti = false
	#Enable Warhammer
	warhammer = false
	#Enable Cushion
	cushion = true
	#Enable Courtroom Items
	courtroom = false
	#Enable Golden Coins
	coins = false
	#Enable Grab Hook
	grab_hook = false
	#Enable Bookcase
	bookcase = false
	#Enable Ender Flask
	flask = false
	#Enable Leather and Straw Blocks
	leather_straw = false
	#Enable Food
	food = false
	#Enable Carved Wood
	carved_wood = true

